// examples/next/app/products/page.tsx
import Link from 'next/link'
import { products } from '../data'

export default function ProductsPage() {
  return (
    <main>
      <Link href="/">← Home</Link>
      <h1>Products</h1>
      <ul>
        {products.map((p) => (
          <li key={p.id}>
            <Link href={`/products/${p.id}`}>
              {p.name} — ${p.price}
            </Link>
          </li>
        ))}
      </ul>
    </main>
  )
}

// examples/nuxt/pages/products/index.vue
<script setup lang="ts">
import { products } from '../../data'
</script>

<template>
  <main>
    <NuxtLink to="/">← Home</NuxtLink>
    <h1>Products</h1>
    <ul>
      <li v-for="p in products" :key="p.id">
        <NuxtLink :to="`/products/${p.id}`">
          {{ p.name }} — ${{ p.price }}
        </NuxtLink>
      </li>
    </ul>
  </main>
</template>
