// examples/nuxt/pages/products/[id].vue
<script setup lang="ts">
import { getPreviousPath } from 'navlens'
import { products } from '../../data'

const route = useRoute()
const router = useRouter()
const product = products.find((p) => p.id === route.params.id)

function handleBack() {
  const prev = getPreviousPath()
  if (prev) {
    router.back()
  } else {
    navigateTo('/')
  }
}
</script>

<template>
  <main>
    <button @click="handleBack">← Back</button>
    <template v-if="product">
      <h1>{{ product.name }}</h1>
      <p>${{ product.price }}</p>
      <p>{{ product.description }}</p>
    </template>
    <p v-else>Product not found.</p>
  </main>
</template>

// examples/sveltekit/src/routes/products/[id]/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { getPreviousPath } from 'navlens'
  import { products } from '$lib/data'
  import { page } from '$app/stores'

  $: product = products.find((p) => p.id === $page.params.id)

  function handleBack() {
    const prev = getPreviousPath()
    if (prev) {
      history.back()
    } else {
      goto('/')
    }
  }
</script>

<main>
  <button on:click={handleBack}>← Back</button>
  {#if product}
    <h1>{product.name}</h1>
    <p>${product.price}</p>
    <p>{product.description}</p>
  {:else}
    <p>Product not found.</p>
  {/if}
</main>
