// examples/react-router/src/pages/ProductsPage.tsx
import { Link } from 'react-router-dom'
import { products } from '../data'

export default function ProductsPage() {
  return (
    <main>
      <Link to="/">← Home</Link>
      <h1>Products</h1>
      <ul>
        {products.map((p) => (
          <li key={p.id}>
            <Link to={`/products/${p.id}`}>
              {p.name} — ${p.price}
            </Link>
          </li>
        ))}
      </ul>
    </main>
  )
}

// examples/quasar/src/pages/ProductsPage.vue
<script setup lang="ts">
import { products } from '../data'
</script>

<template>
  <q-page padding>
    <router-link to="/">← Home</router-link>
    <h1>Products</h1>
    <q-list>
      <q-item
        v-for="p in products"
        :key="p.id"
        clickable
        :to="`/products/${p.id}`"
      >
        <q-item-section>{{ p.name }} — ${{ p.price }}</q-item-section>
      </q-item>
    </q-list>
  </q-page>
</template>
